{
 "title": "Logs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Consensus details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apphash",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{unit=\"story.service\"} |= `committed`"
    },
    {
     "expr": "{unit=\"validator.service\"} |= `Committing a subdag`"
    }
   ]
  },
  {
   "title": "Excuted blocks",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{unit=\"story.service\"} |= `executed block`"
    },
    {
     "expr": "{unit=\"validator.service\"} |= `Committing a subdag`"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{unit=\"story.service\"} |~ `WARN`"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{unit=\"story.service\"} |= `ERR`"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{unit=\"story.service\"}"
    }
   ]
  }
 ]
}