global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["172.17.0.1:9100"]
  - job_name: story
    static_configs:
      - targets: ['172.17.0.1:26660']
